# Generated by Django 3.1.1 on 2020-10-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='null', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
